[profile.default]
solc = '0.8.20'
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'solady/=lib/solady/src/',
    'solady-test/=lib/solady/test/',
    'solarray/=lib/solarray/src/',
]
bytecode_hash = 'none'
cbor_metadata = false
optimizer_runs = 1_000_000
# via_ir = true

[rpc_endpoints]
polygon_mumbai = "${MUMBAI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
