[profile.default]
solc = '0.8.20'
src = "src"
out = "out"
libs = ["lib"]
remappings = ['solady/=lib/solady/src/', 'solady-test/=lib/solady/test/']
bytecode_hash = 'none'
cbor_metadata = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
